<?php

namespace app\index\controller;

use think\Controller;
use think\Request;

class Cross extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

//        header('Access-Control-Allow-Origin:*'); //支持全域名访问，不安全，部署后需要固定限制为客户端网址

        header('Access-Control-Allow-Origin: http://localhost:8080');

        header('Access-Control-Allow-Methods:POST,GET,OPTIONS,DELETE'); //支持的http 动作

        header('Access-Control-Allow-Headers:Origin,x-requested-with,content-type,Accept,x-access-sign,x-access-time'); //响应头 请按照自己需求添加。

        if (request()->isOptions()){
            exit();
        }
    }
}
